# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: electronuserland/builder

pipelines:
  # default:
  tags:
    'v*':
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - yarn
            - yarn build:win
  custom:
    'test-build':
      - step:
          caches:
            - node
          script: # Modify the commands below to build your repository.
            - apt-get update && apt-get install -y --install-recommends wine-stable
            - yarn
            - yarn build:win